### PR TITLE
EDU-2233-sso-reference

### PR DESCRIPTION
**Pull request by mariiaguirre**
Atualização da doc conforme template de reference.

### CODE REVIEW

**Review by bru-andrade — APPROVED** [review]
👯

**Review by gabriel-azion — CHANGES_REQUESTED** [review]
some typos and other things. Let me know when the corrections are applied.

**Review by hannah-sk — CHANGES_REQUESTED** [review]
alguns typos e espaços sobrando

**Review by MarianaAguilera — APPROVED** [review]
approved, with the comments/suggestions.

**Review by hannah-sk — APPROVED** [review]

**Review by gabriel-azion — APPROVED** [review]

**Pull request merged**
